name: smoking_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  audioplayers: ^6.4.0
  vibration: ^3.1.3
  flutter_phoenix: ^1.1.1 
  velocity_x: ^4.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.2.5
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5 # Storage
  firebase_messaging: ^15.2.5 # Push Notifications
  firebase_auth: ^5.5.3
  intl: ^0.20.2
  synchronized: ^3.0.0
  http: ^1.4.0
  flutter_markdown_plus: ^1.0.3
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  android_intent_plus: ^4.0.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  flutter_linkify:





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon2.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/beep.mp3
    - assets/audios/pacman_intermission.wav

