// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnuzvbdtE7sI6sTdaEaRaAV-SXqGP2DeU',
    appId: '1:910101302741:web:b9483793488c96989c015c',
    messagingSenderId: '910101302741',
    projectId: 'smoking-app-7aea6',
    authDomain: 'smoking-app-7aea6.firebaseapp.com',
    storageBucket: 'smoking-app-7aea6.firebasestorage.app',
    measurementId: 'G-RT3WXPTTRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2B33XZGVhtYu_avfEWawzGIt2eCfZDZo',
    appId: '1:910101302741:android:bcfa85dfd76469369c015c',
    messagingSenderId: '910101302741',
    projectId: 'smoking-app-7aea6',
    storageBucket: 'smoking-app-7aea6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtRVffn2y2-mfQ3vecCbyCbIkYm7jaqIY',
    appId: '1:910101302741:ios:a939dc2ba42e76db9c015c',
    messagingSenderId: '910101302741',
    projectId: 'smoking-app-7aea6',
    storageBucket: 'smoking-app-7aea6.firebasestorage.app',
    iosBundleId: 'com.example.smokingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtRVffn2y2-mfQ3vecCbyCbIkYm7jaqIY',
    appId: '1:910101302741:ios:a939dc2ba42e76db9c015c',
    messagingSenderId: '910101302741',
    projectId: 'smoking-app-7aea6',
    storageBucket: 'smoking-app-7aea6.firebasestorage.app',
    iosBundleId: 'com.example.smokingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnuzvbdtE7sI6sTdaEaRaAV-SXqGP2DeU',
    appId: '1:910101302741:web:f8c1781e5c7dd3779c015c',
    messagingSenderId: '910101302741',
    projectId: 'smoking-app-7aea6',
    authDomain: 'smoking-app-7aea6.firebaseapp.com',
    storageBucket: 'smoking-app-7aea6.firebasestorage.app',
    measurementId: 'G-1BBR44M6GH',
  );
}
